name = "templatecatalog01-cc-by-nc"

account_id = "448a5b0c80d31dbd28fe2e8afdd9a050"
workers_dev = true
compatibility_date = "2025-11-20"
compatibility_flags = []

main = "worker.js"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[build]
upload_source_maps = false

[[kv_namespaces]]
binding = "sessionState"
id = "46fb877c8a0d4d4ea1c7cd58732d555f"

[[d1_databases]]
binding = "Data"
database_name = "template_comerce01"
database_id = "f804454f-52f2-44cb-aaa0-30ebee5c36db"

[vars]
#tokens_G = "GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GOOGLE_REFRESH_TOKEN,DRIVE_FOLDER_ID"
#bot_Token = "BOT_TOKEN,SECRET_TOKEN,CHAT_ID"
#tokenSite = "URL_ORIGEM_AUTORIZADA,TOKEN_PAGINA,TOKEN_AUTENTICACAO"